// ============================================
// Medical Knowledge Graph Schema
// Generated by schema.py
// ============================================

// ===== Unique Constraints =====
CREATE CONSTRAINT disease_name_unique IF NOT EXISTS
FOR (n:Disease) REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT symptom_name_unique IF NOT EXISTS
FOR (n:Symptom) REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT medication_name_unique IF NOT EXISTS
FOR (n:Medication) REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT department_name_unique IF NOT EXISTS
FOR (n:Department) REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT bodypart_name_unique IF NOT EXISTS
FOR (n:BodyPart) REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT examination_name_unique IF NOT EXISTS
FOR (n:Examination) REQUIRE n.name IS UNIQUE;

CREATE CONSTRAINT food_name_unique IF NOT EXISTS
FOR (n:Food) REQUIRE n.name IS UNIQUE;

// ===== Indexes =====
CREATE INDEX disease_icd_code_idx IF NOT EXISTS
FOR (n:Disease) ON (n.icd_code);

CREATE INDEX symptom_severity_idx IF NOT EXISTS
FOR (n:Symptom) ON (n.severity);

CREATE INDEX medication_category_idx IF NOT EXISTS
FOR (n:Medication) ON (n.category);

CREATE INDEX bodypart_system_idx IF NOT EXISTS
FOR (n:BodyPart) ON (n.system);

CREATE INDEX examination_type_idx IF NOT EXISTS
FOR (n:Examination) ON (n.type);

CREATE INDEX food_type_idx IF NOT EXISTS
FOR (n:Food) ON (n.type);

CREATE INDEX precaution_category_idx IF NOT EXISTS
FOR (n:Precaution) ON (n.category);

// ===== Verification =====
CALL db.constraints();
CALL db.indexes();